org: pikimell
service: lyrics-api

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  profile: serverlessUser
  timeout: 20

functions:
  createPlaylist:
    handler: src/handlers/playlistHandlers.createPlaylistHandler
    events:
      - http:
          path: playlists
          method: post
          cors: true

  updatePlaylist:
    handler: src/handlers/playlistHandlers.updatePlaylistHandler
    events:
      - http:
          path: playlists/{id}
          method: put
          cors: true

  deletePlaylist:
    handler: src/handlers/playlistHandlers.deletePlaylistHandler
    events:
      - http:
          path: playlists/{id}
          method: delete
          cors: true

  getPlaylist:
    handler: src/handlers/playlistHandlers.getPlaylistHandler
    events:
      - http:
          path: playlists/{id}
          method: get
          cors: true

  listPlaylists:
    handler: src/handlers/playlistHandlers.listPlaylistsHandler
    events:
      - http:
          path: playlists
          method: get
          cors: true
